openapi: 3.0.3
info:
  version: 1.0.0
  title: Bus Live Fare And Location Service API
  description: This service is responsible for providing these details - Latest fare information; Realtime bus location stream that representing movements of all buses in the fleet.

paths:
  /buses/{id}/fare:
    get:
      description: Fetch bus fare by vehicle id
      parameters:
        - name: id
          description: Given a bus id we need to fetch older version of fare.
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusFare'
  /location-stream:
    get:
      description: Location stream
      responses:
        '200':
          description: Successful response
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/BusLocationStream'
components:
  schemas:
    BusFare:
      required:
        - id
        - fare
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        fare:
          type: integer
          format: int64
          example: 201
    BusLocationStream:
      type: array
      items:
        $ref: '#/components/schemas/BusLocation'
    BusLocation:
      required:
        - id
        - location
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        location:
          required:
            - lat
            - lng
          type: object
          properties:
            lat:
              type: integer
              format: int64
              example: 11
            lng:
              type: integer
              format: int64
              example: 11
