openapi: 3.0.3
info:
  version: 1.0.0
  title: Train Live Location Service API
  description: This service is responsible for providing these details - Realtime stream of locations all trains.
paths:
  /location-stream:
    get:
      description: Location stream
      responses:
        '200':
          description: Successful response
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/TrainLocationStream'
components:
  schemas:
    TrainLocationStream:
      type: array
      items:
        $ref: '#/components/schemas/TrainLocation'
    TrainLocation:
      required:
        - id
        - location
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        location:
          required:
            - lat
            - lng
          type: object
          properties:
            lat:
              type: integer
              format: int64
              example: 11
            lng:
              type: integer
              format: int64
              example: 11
