openapi: 3.0.3
info:
  version: 1.0.0
  title: Vehicle Aggregator Service API
  description: This service is responsible for exposing API endpoints that aggregate data from dependent micro services & meet business constraints.
paths:
  /buses:
    get:
      description: List of aggregated buses with fares
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusWithFareList'
  /vehicle-location-stream:
    get:
      description: Aggregated location stream of all vehicles (buses & trains)
      responses:
        '200':
          description: Successful response
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/VehicleLocationStream'
components:
  schemas:
    BusWithFareList:
      type: array
      items:
        $ref: '#/components/schemas/BusWithFare'
    BusWithFare:
      required:
        - id
        - licensePlate
        - fare
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        licensePlate:
          type: string
          example: BUS1
        fare:
          type: integer
          format: int64
          example: 101
    VehicleLocationStream:
      type: array
      items:
        $ref: '#/components/schemas/VehicleLocation'
    VehicleLocation:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        type:
          type: string
          example: BUS
        location:
          type: object
          properties:
            lat:
              type: integer
              format: int64
              example: 11
            lng:
              type: integer
              format: int64
              example: 11
