openapi: 3.0.3
info:
  version: 1.0.0
  title: Bus Metadata Service API
  description: This service is responsible for providing metadata about buses. Bus metadata consists of id & licensePlate.
paths:
  /metadata:
    get:
      description: Get Metadata
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusMetadataList'
components:
  schemas:
    BusMetadataList:
      type: array
      items:
        $ref: '#/components/schemas/BusMetadata'
    BusMetadata:
      required:
        - id
        - licensePlate
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        licensePlate:
          type: string
          example: BUS1
