openapi: 3.0.3
info:
  version: 1.0.0
  title: Bus Fallback Fare Service API
  description: This service is responsible for providing these details - Outdated fare information.
paths:
  /buses/{id}/fare:
    get:
      description: Fetch bus fare by vehicle id
      parameters:
        - name: id
          description: Given a bus id we need to fetch older version of fare.
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusFare'
components:
  schemas:
    BusFare:
      required:
        - id
        - fare
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        fare:
          type: integer
          format: int64
          example: 201
